config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'
  resources :employees do
    collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
# frozen_string_literal: true

# defines Model, validations, and methods to import and export data in csv format
class Employee < ApplicationRecord
  VALID_PHONE_NUMBER = /\A[0-9]+\Z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email,
            presence: true,
            uniqueness: { scope: :full_name, message: 'already exists in the database' },
            length: { minimum: 3, maximum: 35 },
            format: { with: VALID_EMAIL_REGEX }

  validates :full_name,
            presence: true,
            length: { minimum: 3, maximum: 25 }
  validates :last_names,
            presence: true,
            length: { minimum: 3, maximum: 25 }
  validates :phone_number,
            presence: true,
            uniqueness: { scope: :id, message: 'already exists in the database'},
            length: { is: 11 },
            format: { with: VALID_PHONE_NUMBER }
  validates :position,
            presence: true,
            length: { maximum: 25 }
  validates :salary,
            presence: true,
            length: { maximum: 15 }
  validates :department,
            presence: true,
            length: { maximum: 25 }

  def self.import(file)
    if file
      # loop through csv file
      CSV.foreach(file.path, headers: true) do |row|
        # creates an user for each row in the file
        Employee.create! row.to_hash
      end
    end
  end

  def self.to_csv
    attributes = %w[full_name last_names email phone_number position salary department]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |employee|
        csv << employee.attributes.values_at(*attributes)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

# defines methods for CRUD, import and export data in csv format
class EmployeesController < ApplicationController
  include ActionView::Helpers::NumberHelper

  before_action :set_employee, only: %i[show index]
  before_action :set_phone_and_salary, only: %i[show index]

  PHONE_PATTERN = /(\d{1,4})(\d{4})(\d{4})$/

  def new
    @employee = Employee.new
  end

  def index
    @employees = Employee.all

    respond_to do |format|
      format.html
      format.csv { send_data @employees.to_csv }
    end
  end

  def show; end

  def create
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'employee was successfully added to the list.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def import
    if Employee.import(params[:file])
      redirect_to employees_path, notice: 'data was just imported!'
    else
      redirect_to employees_path, alert: 'Sorry, No file chosen, Action can not be performed'
    end
  rescue ActiveRecord::RecordInvalid => e
    redirect_to employees_path, alert: "#{e.message}, it seems your file has duplicated records"
  end

  private

  def set_phone_and_salary
    @phone_number = number_to_phone(@employee.phone_number, pattern: PHONE_PATTERN, area_code: true)
    @salary = number_to_currency(@employee.salary, separator: ',', delimiter: '.')
  end

  def set_employee
    @employee = Employee.find_by(params[:id])
  end

  def employee_params
    params.require(:employee).permit(
      :full_name,
      :last_names,
      :phone_number,
      :email,
      :position,
      :salary,
      :department
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(employee.errors.count, "error") %> 
          prohibited this employee from being saved:
      </h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group" >
    <%= form.label :full_name, 'Nombres' %>
    <%= form.text_field :full_name, class:"form-control form-control-sm" %>
  </div>

  <div class="field form-label">
    <%= form.label :last_names, 'Apellidos' %>
    <%= form.text_field :last_names, class:"form-control form-control-sm" %>
  </div>
  
  <div class="field form-label">
    <%= form.label :phone_number, 'Nùmero De Telèfono' %>
    <%= form.text_field :phone_number, class:"form-control form-control-sm" %>
  </div>
  
  <div class="field form-label">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control form-control-sm" %>
  </div>

  <div class="field form-label">
    <%= form.label :position, 'Cargo' %>
    <%= form.text_field :position, class:"form-control form-control-sm" %>
  </div>
  <div class="field form-label">
    <%= form.label :salary, 'Salario' %>
    <%= form.text_field :salary, class:"form-control form-control-sm" %>
  </div>

  <div class="field form-label">
    <%= form.label :department, 'Departamento' %>
    <%= form.select :department, ['Contabilidad', 
                                  'Finanzas', 
                                  'Operaciones', 
                                  'Seguridad', 
                                  'Recursos Humanos'], 
                                  selected: 'Operaciones', 
                                  class:"form-control form-control-lg" %>
  </div>
  <br>
  
  <div class="actions form-label">
    <%= form.submit class:"btn btn-primary"%>
  </div>

<% end %>

app/views/employees/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Contact App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Add Employee", new_employee_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Employees", employees_path, class:"nav-link" %>
        </li>
         
      </ul>
    </div>
  </div>
</nav>

app/views/employees/index.html.erb
<h1>Employees</h1>
  

<div class="container">
  <h3> Download data from Data Base</h3>
  <%= link_to 'download', employees_path + '.csv', class:"btn btn-outline-secondary" %>
  <br>
  <h3> Import data from your pc</h3>
    <%= form_tag import_employees_path, multipart: true do %>
      
      <%= file_field_tag :file %>
      <%= submit_tag 'import CSV' %>
    <% end %>
</div>
<br>

<br>
<% @employees.each do |employee| %>
<b>-------------------------------------</b>
  <p class="fs-7">
    <strong>
      Role:
    </strong>
  <%= employee.class %>
  </p>
  <p class="fs-2">
    <strong>
      Nombres:
    </strong>
    <p><%= employee.full_name %></p>
    <strong>
      Apellidos:
    </strong>
    <p><%= employee.last_names %></p>
    <strong>
      Email:
    </strong>
    <p><%= employee.email %></p>
    <strong>
      Cargo:
    </strong>
    <p><%= employee.position %></p>
    <strong>
      Departamento:
    </strong>
    <p><%= employee.department %></p>
    <strong>
      Salario:
    </strong>
    <p><%= @salary %></p>
    <strong>
      Nùmero De Telèfono:
    </strong>
    <p><%= @phone_number %></p>
  </p>

 <p>------   ------</p>
<% end %>
<%= link_to 'Back', new_employee_path, class:"btn btn-danger" %>

app/views/employees/new.html.erb
<h1>New Employee</h1>
<div class="container">
  <%= render 'form', employee: @employee, class:"btn btn-success" %>
  <%= link_to 'Back', employees_path, class:"btn btn-danger" %>
</div>

app/views/employees/show.html.erb
<h1>Employee</h1>
<div>
  <p>
    <b>
      Nombres: 
    </b> 
    <%= @employee.full_name %>
  </p>
  <p>
    <b>
      Apellidos: 
    </b> 
    <%= @employee.last_names %>
  </p>
  <p>
    <b>
      Email: 
    </b> 
    <%= @employee.email %>
  </p>
  <p>
    <b> 
      Telefono: 
    </b>
    <%= @phone_number %>
  </p>
  <p>
    <b> 
      Salario: 
    </b>
    <%= @salary %>
  </p>
  <p>
    <b> 
      Cargo: 
    </b> 
    <%= @employee.position %>
  </p>
  <p>
    <b>
      Departamento: 
    </b> 
    <%= @employee.department %>
  </p>
</div>
<%= link_to 'Back', new_employee_path, class:"btn btn-danger" %>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>EmployeeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'employees/header' %>
    <br>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>